{"name": "Тест: ошибка 404 not found при передаче несуществующего password", "status": "passed", "attachments": [{"name": "log", "source": "a2757912-711d-4830-a56a-68649922bfc3-attachment.txt", "type": "text/plain"}], "start": 1717768240149, "stop": 1717768240429, "uuid": "0f487adb-96e8-4375-9dff-1aee3b4ca486", "historyId": "ce11455102f9e6ad31818c48ba7af205", "testCaseId": "ce11455102f9e6ad31818c48ba7af205", "fullName": "tests.test_login_courier.TestPostLoginCourier#test_login_courier_with_non_existent_password_shows_error_404", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestPostLoginCourier"}, {"name": "host", "value": "DESKTOP-USF6L0H"}, {"name": "thread", "value": "8512-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}