{"name": "Тест: ошибка 404 not found при передаче несуществующего password", "status": "passed", "attachments": [{"name": "log", "source": "4d9a8bcb-b1f8-4b40-86df-53dcfd7fc707-attachment.txt", "type": "text/plain"}], "start": 1717679537862, "stop": 1717679538177, "uuid": "114d119a-5647-451c-8055-8a14363dc1e1", "historyId": "ce11455102f9e6ad31818c48ba7af205", "testCaseId": "ce11455102f9e6ad31818c48ba7af205", "fullName": "tests.test_login_courier.TestPostLoginCourier#test_login_courier_with_non_existent_password_shows_error_404", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestPostLoginCourier"}, {"name": "host", "value": "DESKTOP-USF6L0H"}, {"name": "thread", "value": "1796-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}