{"name": "Тест: ошибка 404 not found при передаче несуществующего password", "status": "passed", "start": 1717930446536, "stop": 1717930446789, "uuid": "a2677c6f-4c5f-4c44-82e9-8dc7919b22de", "historyId": "ce11455102f9e6ad31818c48ba7af205", "testCaseId": "ce11455102f9e6ad31818c48ba7af205", "fullName": "tests.test_login_courier.TestPostLoginCourier#test_login_courier_with_non_existent_password_shows_error_404", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestPostLoginCourier"}, {"name": "host", "value": "DESKTOP-USF6L0H"}, {"name": "thread", "value": "16456-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}